### ISSUE TITLE
using LRT in DESeq 2

### ISSUE THREAD

**Issue by jscaber** [williamritchie/IRFinder#129]
Hi,

Thanks for this helpful tool. I don't  much IR in my dataset(s), but what there is this seems to find pretty well, with fewer false positives that I am used from other splicing analyses.

I don't see any contracintications for adding a confounder in the DESeq part of the IRFinder analysis, like so:
~ grp + grp:confounder + grp:IRFinder
I'm checking in case I am misunderstanding the IRFinder term in the model. Obviously, if unevenly distributed, the model matrix may need to be adjusted.
Is there a possibility to specify a reduced model in the IRFinder DESeq analysis?

Bw,
Jakub

**Comment by dg520** [comment]
@jscaber ,
This is a good question. We did not include confounding factors in the regression equation because we assume they would have the same effect size on both exonic and intronic reads. As IR is measured as a ratio (i.e. intronic/(exonic + intronic)), this would cancel out the effect from confounders.

With that said, you can still estimate the confounding effect, for example:
```
design(dds) = ~grp + CONFOUNDER + grp:IRFinder
``` 
(I don't think you need `grp:CONFOUNDER`, unless there is a reason to believe the two terms have interactions)
Then estimate each effect and run the test:
```
dds = DESeq(dds, test="LRT", reduced = ~ 1)
#Alternatively, you can do
# dds = DESeq(dds, test="LRT", reduced = ~Condition + CONFOUNDER)
# or
# dds = DESeq(dds, test="LRT", reduced = ~CONFOUNDER)
# based on which terms you care about in the downstream analysis
```

**Comment by jscaber** [comment]
Thanks @dg520 
That's very helpful. I have inherited a dataset with subject variation in the dataset including a sex difference that is unbalanced (but not perfectly confounded). I have found GLMs to be poor at correcting such complex confounders, if not appropriately addressed at the experimental design stage, but I'll give it a try, if anything useful emerges I'll let you know here. 

You're right about not needing `grp:confounder`. 
(I had actually wondered about the possible interaction between sex and intron retention, which is not unlikely, but does not need to be separately stated in the GLM.)
