### ISSUE TITLE
Issue building the reference

### ISSUE THREAD

**Issue by seanbyars** [williamritchie/IRFinder#146]
Hi there,

I'm using IRFinder for the first time and am trying to build the reference from the Ensembl FTP site with...

IRFinder -m BuildRef -r ReferenceDir ftp://ftp.ensembl.org/pub/release-100/gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz

...first few times it ran out of memory and I got a memory specific warning on the server, so upped the memory to 80GB and it ran to Phase 3 (IR Reference Preparation) up to ...building Ref 11c... and then just ended with NO error messages (see attached).

My question is, when it gets to 'building Ref 11c' and finishes with no error messages, does this mean its completed successfully?? Or should I expect to see additional completion messages beyond this to say its finished successfully?

![Screen Shot 2021-08-13 at 12 04 36 pm](https://user-images.githubusercontent.com/88866766/129294875-74d5dcf1-46f7-46df-a353-d6dc42f6afd9.png)

**Comment by dg520** [comment]
@seanbyars Are you using v1.3.1? If so, Ref 11c is the last step of reference building. You've successfully built all references if you didn't see any error line after it and your cursor returned normally. That is the expected behavior, so I'll close this thread. Feel free to re-open it if you have following questions related to this topic. Otherwise, please open a new thread for new topics. Thanks.

**Comment by seanbyars** [comment]
Thanks for the quick reply! Yes, I am using v1.3.1 and I had also double checked for any temporary (tmp) files (which there weren't) in any of the auto-created folders that would also suggest the pipe hadn't completed. Thanks, this confirms that its run to completion :)
