### ISSUE TITLE
Force the output of IRFinder-IR-dir.txt?

### ISSUE THREAD

**Issue by viktor-hub** [williamritchie/IRFinder#154]
First, thank you so much for this wonderful tool! I'm encountering issues with certain timepoints of a stranded RNA-seq experiment where they do not pass IRFinder's directionality test. I am guessing that this may be happening due to splicing being severely impacted under certain conditions. Is there any way to force or modify a line of code in IRFinder, or alter the annotation file being used, so that it outputs the IRFinder-IR-dir.txt file associated with directional RNA-seq? I would like to conduct a consistent differential IR analysis across all of the samples using the directional IRFinder output. Thank you very much!

**Comment by dg520** [comment]
@viktor-hub Before changing the source code, could you please show me the last 9 lines in `irfinder.stdout`?

**Comment by viktor-hub** [comment]
@dg520 Yes, this is an RNA-seq experiment we conducted.

1. This is an alga - the genome is relatively compact at ~20 Mb, and there are surprisingly only ~40 introns.
2. There are 13 and 16 million paired reads, respectively, for the samples shown above.
3. The uniquely mapped reads reported by STAR are 81% and 89%.

The alignment looks good in IGV. We've used IRFinder on hundreds of samples now, and this is occurring (consistently among many replicates) with one particular experimental condition.

**Comment by dg520** [comment]
@viktor-hub Thanks for the clarification. Just wanna make sure we would shoot at the right problem. To achieve what you asked originally, please modify Line 182 AND Line 185 in `IRFinder/src/irfinder/ReadBlockProcessor.cpp`.    
Note:
1. the variable `dir_same` records the number of the output line "Directionality: Dir matches ref:"      
2. the variable `dir_diff` records the number of the output line "Directionality: Dir opposed to ref:"      
3. the variable `dir_evidence_known` records the number of the output line "Directionality: Dir evidence known junctions:"      
4. the variable `nondir_evidence_known` records the number of the output line "Directionality: Nondir evidence known junctions:"      
5. the variable `dir_score_known` = (`dir_same` + `dir_diff`) * 10000 / (`dir_same` + `dir_diff` + nondir_evidence_known + 1)     
6. Whatever cutoff you want to use, you have to make the same changes to both Line 182 AND Line 185. Otherwise, the quantification might be problematic.
7. You have to re-compile the `irfinder` core after making changes and replace the original core with the new one. Please see [here](https://github.com/williamritchie/IRFinder/wiki/Download-and-Install#compilation-optional)

**Comment by beaferbl** [comment]
Hi!,
I am having the same problem. My library is first-stranded, but the directionality is not detected for only one sample. This is the output:
Error reads: 0
Directionality: Dir evidence:	107631
Directionality: Nondir evidence:	16524
Directionality: Dir evidence known junctions:	93240
Directionality: Nondir evidence known junctions:	15947
Directionality: Dir matches ref:	231
Directionality: Dir opposed to ref:	93009
Directionality: Dir score all (0-10000):	8669
Directionality: Dir score known junctions (0-10000):	**8539**
RNA-Seq directionality -1/0/+1:	0

As I see, the cutoff is 9000, but 8539 is very near to 9000. So if I want to force IRFinder to consider it as stranded, I could set a lower cutoff as you say. This can work in this case, but I should change the script and recompile every time I don't get the desired results, because this can happen again with other samples. 
So I have two questions:
1. Would it be nice to use the IR-non-dir.txt output for this sample and the IR-dir.txt for the rest? What would be the impact on the results?
2. How was the value 9000 choosen? Because if I decide to set it to a lower value, I don't have no idea which value could be logical to work in general.
Best,
Bea

**Comment by dg520** [comment]
@beaferbl 
1. There are two sets of IRFinder reference, one for directional libraries and the other for non-directional ones. The difference between the two sits in the intronic sub-regions considered to be excluded during the IR ratio calculation. This should be reflected in Columns 7, 8 & 9 of the two output files `IR-non-dir.txt` and `IR-dir.txt`. The values in these three columns impact the final IR ratio in Column 20.
2. A perfect directionality score is set as 10000. So, 9000 is trivial and just the 90% of perfect. We have tested more than 2500 publicly available directional RNASeq libraries and found 9000 is a very faithful cutoff to use. But you can definitely change it to a value better fit your customized library if you feel confident and comfortable. You can find the step to achieve this a bit above in this thread.

**Comment by beaferbl** [comment]
I understand know, thank you for the answer.
