### ISSUE TITLE
DIR Analysis ~ DESeq2 vs Audic and Claverie test

### ISSUE THREAD

**Issue by LedaKatopodi** [williamritchie/IRFinder#156]
hello~!

I would like to gain some insight into your decision to switch from the Audic and Claverie test to the DESeq2/GLM approach, for >= 3 replicates. 

if I am not mistaken, until recently the suggested approach for DIR analysis was the Audic and Claverie test for 3 replicates. could you explain the reasoning behind the change? what are the advantages of the GLM approach? can the Audic and Claverie test be used for DIR analysis with 3 replicates? it would also be extremely useful to provide further documentation for the IRFinder x DESeq2 approach; it would make it so much easier for understanding the steps of the analysis, as well as for traceback and troubleshooting. 

as an example, for the analysis I am currently running, the number of significant diff retained introns I get from the GLM approach are far less (0 sig diff retained introns) than the ones I get with the Audic and Claverie test (107 sig diff retained introns), for 3 replicates. why do I observe such big differences? which method should I trust more? expanding the GLM documentation would also help with understanding.

thank you for building this fantastic tool -which I hope I am using properly.

cheers,
Leda

**Comment by dg520** [comment]
@LedaKatopodi GLM-based approach has been introduced into IRFinder since 2017. Please note, **we are not replacing Audic-Claverie test**. Instead, we just provide alternative options for users in case they need. 

Some key differences between Wald test (i.e. the test used by GLM approach) and Audic-Claverie test are as following:
1. **Distribution assumption**: Wald test assumes negative binomial distribution while Audic-Claverie test assumes Poisson distribution
2. **Requirement for replicates**: Because of the above point, Wald test requires replicates to calculate dispersion. In another word, it's impossible to do 1-vs-1 comparison using Wald test. On the other hand, Audic-Claverie test was originally designed for 1-vs-1 comparison. We had to tweak it to adapt 2-vs-2 and 3-vs-3 comparisons, with the realization that its performance drops with more biological replicates (e.g, 4-vs-4). Audic-Claverie test is unable to compare imbalanced design (e.g. 2-vs-3) while GLM can.
3. **Null hypothesis**: For Wald test, it examines whether the _fold change_ of intron expression is 1. For Audic-Claverie test, it examines whether the _counts difference_ of intron expression is 0. 

One thing that is only available in GLM-base approach is the capability of modelling confounding factors (e.g. batch effect). That is impossible for Audic-Claverie approach at all.

I don't think you should use number of differential events to judge which method is better. Instead, you need to investigate your data (e.g. check distribution, investigate PCA, etc), together with the previous findings from the similar data (e.g. literature), before deciding which method is better. 

Finally, the GLM approach we used here is adapted from DESeq2, it has a very comprehensive documentation [here](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html).

**Comment by LedaKatopodi** [comment]
hi @dg520,

thank you for the detailed and thorough answer!

with regards to the documentation, indeed the DESeq2 vignette you redirect me to is one of the most comprehensive sources available. however, I am not sure it can answer the question on how IRFinder's approach can estimate differentially retained introns _through_ DESeq2. 

to elaborate, I would like to learn more about why the model was chosen in a way that introduces IRFinder as an interaction term and not as the main term. also, I understand that the KO/normal vs WT/normal comparison takes place because of the definition of IR-ratio, is that correct? why not compare raw (or normalized) counts on introns for that matter (IR-ratio being one thing, and differentially retained introns another)?

regarding the Audic-Claverie test with 3 replicates, I have been successfully carrying out such analyses since 2019. for the vast majority of the top sig genes (p-diff < 0.05) the results were backed up by visualization tools and genome browsers.

again, I would like to thank you for this fantastic tool and for helping me understand it.

cheers,
Leda

**Comment by dg520** [comment]
@LedaKatopodi 
Sorry for a late reply, as I just got back from vocation.

First. let's talk about your application of Audic-Clarvarie (A-C) test with multiple replicates. Please DO note, this approach only works with TWO replicates, as demonstrated [here](https://github.com/williamritchie/IRFinder/wiki/Small-Amounts-of-Replicates-via-Audic-and-Claverie-Test).  I think you got confused by the final command in that demo. That command shows three input files for `-A` and `-B` respectively, however, they do NOT represent three replicates. Instead, they are two replicates plus one merged sample from these two replicates, if you read that page from top carefully. Very import to know, this merged sample serves as an overall control for variance between the two replicates. Thus, it CANNOT be replaced by a third replicate. Otherwise, it won't control for variable but will introduce more variance, and it totally disrupts the statistical framework tweaked from the original A-C test, which only works on 1-vs-1 comparison.

Now let's talk about GLM application via DESeq2 package. You can definitely put `IRFinder` as a main term and the regression equation will become:
```
design(dds) ~ Condition + IRFinder + Condition:IRFinder
```
This is just a transformed equation of the one in the tutorial. What is the difference? The terms you get from this transformation are slightly different. You can try that yourself by further running the following:
```
dds = DESeq(dds)
resultsNames(dds)
```
You will see an output something like:
```
[1] "Intercept"                   "Condition_KO_vs_WT"   
[3] "IRFinder_IR_vs_Splice" "ConditionKO.IRFinderIR"
```
Now, your current term[3], namely `IRFinder_IR_vs_Splice` is totally equivalent to the term[3] in the tutorial, namely `ConditionWT.IRFinderIR`. Both of them represent IR's effect on intercept. The intercept in both equations means WT_Splice. The naming difference only reflects your newly included `IRFinder` term.
You will find your current term[4] has the exact same name of that in the tutorial, which is `ConditionKO.IRFinderIR`. HOWEVER, they mean DIFFERENT things. In your current equation, term[4] means ADDITIONAL IR effect on KO_Splice, compared to IR effect on KO_WT (which is term[3]). On the other hand, the term[4] in the tutorial means the full IR effect on KO_Splice. 
Thus, if you want to get the full IR effect on KO_Splice from your current equation, you need to sum your current term[3] and term[4]. In another word, term[4] in the tutorial = your current term[3] + current term[4]

As you can see, there is nothing wrong to put `IRFinder` term in the equation. It just requires one extra step to get full IR effect on KO_Splice. If you are still confusing, I encourage you to read a textbook of basic linear algebra.  Alternatively, [here](https://learning.edx.org/course/course-v1:HarvardX+PH525.2x+2T2016/home) is a series of free online lectures on linear algebra in video format.

To answer your final question that why we focus on IR ratio comparison instead of directly comparing intron expression, let's think of this example:
In condition A, Intron X expresses at 1 CPM while its hosting gene expresses at 100 CPM.
In condition B, Intron X expresses at 0,1 CPM while its hosting gene expresses at 10 CPM.
If you compare intron expression only, you would see a 10-fold decrease. However, the hosting gene's expression has also shrunk 10-fold. In this case, we cannot really tell if this change of intron is due to intron retention or the gene expression.

**Comment by LedaKatopodi** [comment]
hi @dg520,

thank you for the detailed and structured reply once again.

regarding the AC test, I understand that the appropriate number of replicates is max 2. in your documentation you used to mention "no more than 3", [here](https://github.com/williamritchie/IRFinder/wiki/Small-Amounts-of-Replicates-via-Audic-and-Claverie-Test/_compare/e8d043b197474ac2bcd6c01c6f1046f7c018a6bc...6b4eae0f082dff9ae4ccb651923de2f72e6e1b39). I think this was what got me confused after all. I will be switching to the GLM from now on.

also, thank you for explaining how you use DESeq2, it's a bit clearer now. and the IR ratio approach makes sense versus comparing normalized intron counts.

I am closing the issue now, thank you for your time.

cheers,
Leda
