### ISSUE TITLE
Differential IR analysis for intron not in ref-cover.bed

### ISSUE THREAD

**Issue by geocarvalho** [williamritchie/IRFinder#175]
Hi, thank you for making this project open-source.
I'm trying to check the second intron of the MED11 gene using the hg38 reference.
According to IGV, we have intron retention in both introns from the MED11 gene.
<img width="910" alt="Screenshot 2023-12-22 at 4 43 33 PM" src="https://github.com/williamritchie/IRFinder/assets/6020773/fffb3460-b3fa-44f6-b60e-6935b4a4029a">

I could notice that the `ref-cover.bed` only has the first intron in it:
```bash
17	4731579	4731750	nd/MED11/ENSG00000161920/+/1/4731574/4731775/201/30/anti-over	0	+	4731579	4731750	255,0,0	1	171	0
17	4731579	4731770	dir/MED11/ENSG00000161920/+/1/4731574/4731775/201/10/clean	0	+	4731579	4731770	255,0,0	1	191	0
```

I was trying to add the second intron to see the intron retention that is present in both MED11 gene's introns, adding something like:

```bash
17      4731911 4732913 nd/MED11/ENSG00000161920/+/1/4731906/4732938/1032/30/anti-over      0       +       4731911 4732913 255,0,0 1       1002    0
17      4731911 4732933 dir/MED11/ENSG00000161920/+/1/4731906/4732938/1032/10/clean      0       +       4731911 4732933 255,0,0 1       1022    0
```

But the `IRFinder-IR-dir.txt` output only shows the output for the first intron

```bash
17      4731574 4731775 MED11/ENSG00000161920/clean     0       +       10      1       9.05195 5       9       15      19      5       16.75   5       16      16      16      0.361327        NonUniformIntronCover
```

Do you have any recommendations?

**Comment by dg520** [comment]
@geocarvalho Your plot suggested the gene covers coordinates around 4,630,00, but the entry you tried to add has coordinates around 4,731,000. This confused me. If I assume you were looking at the right gene and coverage pattern in IGV, those peaks in your intron2 are more like to be a mixture of UTR expression and unknown exon expression rather than IR.           
       
Generally speaking, IRFinder needs to see a "clean" intronic region before it can build the reference and carry out a measurement. Direct editing of `ref-cover.bed` won't work.      
By "clean", it means but not limited to:     
1) a part of the pure intronic region without other overlapping features on both of the DNA strands. The 5' end of your Intron2 has a long stretch of overlap with 3' UTR of the transcript MED11-202/ENST00000573708.      
2) By excluding the overlapped features, the remainder of the intron should be a) more than 40 bp and b) the remainder part is more than 70% of the original intron length. Your Intron2 is likely to fail this criterion.       
3) And the remainder part of the intron should have high mapability.  I think your Intron2 might be OK for this criterion.     
        
Because the coverage pattern doesn't look like IR, I don't recommend you force the Intron2 measurement. That would lead to wrong biological conclusions. But if you really want to see Intron2 in the IRFinder reference, you can edit Line 82 in the `bin/util/IntronExclusion.pl` by changing 0.7 to a lower number (e.g. 0.4). Then you need to save the edit and re-run the IRFinder reference preparation steps from scratch.        
      
Note: The use of this GitHub Issues page is supposed to fix bugs and solve errors instead of helping users customize this tool. What you've seen is a design of IRFinder, not a bug or error. There is no guarantee the above edition will make your Intron2 appear in the reference.

**Comment by geocarvalho** [comment]
Thank you @dg520 for the explanation.
I thought it could be a feature of possible improvement, but I was wrong.
