### ISSUE TITLE
Using Tophat2 results

### ISSUE THREAD

**Issue by ali0010** [williamritchie/IRFinder#22]
Hi!
I have not had much success with using the BAM mode of IRFinder on the bam file outputs of Tophat2. I keep getting  results with 0 counts ( 0 read counts and 0 junction counts). Note that the chromosome names in the bam files tat I am using start with "chr" , i.e. they are "chr1", "chr2", ..., "chrX", "chrY", so: 
**I)** I once 'reheader'ed the bam files so that they will loose the  "chr" from the begining of the chromosome names and used the ENSEMBL to build reference (BuildRef) with IRFinder; 
**II)** I once again, built the reference (BuildRef) on modified files from ENSEMBL and Human_hg19_nonPolyA_ROI_mod.bed  that "chr" was added to the begining of the chromosome names and used the unmodified bam files resulted by Tophat 2 which also had "chr" in the begining of the chromosome names.

Running IRFinder in BAM mode in both cases (**I** and **II**) returned zero counts of IR and splicing.
Could you please let me know how I can make IRFinder work in BAM mode ?

Cheers,

**Comment by dg520** [comment]
Hi @ali0010,

Please note that in `BAM` mode, the BAM input file **MUST be name-sorted** (equal to unsorted for most of aligner. You can check several lines for that) instead of coordinate-sorted. This is notified both in the IRFinder usage and on the wiki page.

If your input is indeed name-sorted, my suggestion would be to re-build the IRFinder reference using the same GTF file for your TopHat2 alignment. In that way, you don't need to dealing with the header staff. Plus, the reference would be more consistent throughout your analysis. You can easily achieve this by using `-m BuildRefProcess` mode to build a local reference. Read wiki for more details.

If that still failed to generate informative result, could you please show me the following:
1) the command your called TopHat with any standard error printed out;
2) the command you built IRFinder reference with any standard error printed out;
3) the command you run IRFinder analysis with any standard error printed out;

P.S. from your current BAM file, you might also want to check the junction coverage for some house keeping gene to see if they are detected. 

Best,
Dadi
