### ISSUE TITLE
Building reference index make empty files

### ISSUE THREAD

**Issue by florealcab** [williamritchie/IRFinder#23]
Hi,

When I run the BuildRefProcess mode, files ref-*.bed if IRFinder folder are empty:

#########@node054 ~/work/poulet2 $ ll index/IRFinder/
total 3944
-rw-r--r-- 1 ######### BIOINFO 3968159 Aug 24 14:26 exclude.directional.bed
-rw-r--r-- 1 ######### BIOINFO   58382 Aug 24 14:26 exclude.omnidirectional.bed
-rw-r--r-- 1 ######### BIOINFO       0 Aug 24 14:26 intergenic.ROI.bed
-rw-r--r-- 1 ######### BIOINFO       0 Aug 24 14:26 introns.unique.bed
-rw-r--r-- 1 ######### BIOINFO       0 Aug 24 14:26 ref-cover.bed
-rw-r--r-- 1 ######### BIOINFO       0 Aug 24 14:26 ref-read-continues.ref
-rw-r--r-- 1 ######### BIOINFO       0 Aug 24 14:26 ref-ROI.bed
-rw-r--r-- 1 ######### BIOINFO       0 Aug 24 14:26 ref-sj.ref

Then, the BAM mode fail, I think it's linked to that. In the file below the output of the program. Do you have an idea of what is going wrong?

[error_log.txt](https://github.com/williamritchie/IRFinder/files/1249110/error_log.txt)

Cheers,

**Comment by dg520** [comment]
Hi @floreal797,

Thanks for reporting. From the first glance, it could be either due to 1) too many chromosomes/contigs in your reference genome, or 2) the maximal number of file opening in your system setting is too low. 

During the IRFinder reference preparing stage, especially mapability building stage, IRFinder opens as many temporary file as your chromosome/contig numbers of your reference genome and several other main output files are opened at the same time. So that the maximal number of file opening PER USER in your system setting should be beyond the sum of this number. 

The easiest way is to increase the system limit. However if you don't have the permission to do that, here is a way that might work around.

First you need to figure out how many unique chromosomes/contigs are there in the GTF file. Then trimming your reference genome to contain only those GTF-recorded chromosomes/contigs. In most cases, this would dramatically reduce the reference genome size. 

This process is not "perfect". The good part is that we are only interested in the annotated introns (IRFinder only calculates IR in annotated introns) so actually genomic sequences beyond the GTF-referenced region give no information to IRFinder. However, please also be aware that reducing the reference genome size might potentially increase the number of FALSE uniquely mapped reads, which could bias the final result. 

Best,
Dadi
