### ISSUE TITLE
error in MacOS: "IRFinder: line 192: /proc/meminfo: No such file or directory"

### ISSUE THREAD

**Issue by aambioinfo** [williamritchie/IRFinder#27]
Dear Dadi

as /proc does not work in MacOS, I obtain the following errors when trying to run IRFinder in macOS 10.12.6:

$ bin/IRFinder -m BuildRef -r REF/Mouse-mm10-release90 -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz -R REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed ftp://ftp.ensembl.org/pub/release-90/gtf/mus_musculus/Mus_musculus.GRCm38.90.gtf.gz

bin/IRFinder: line 192: /proc/meminfo: No such file or directory
bin/IRFinder: line 193: /1000: syntax error: operand expected (error token is "/1000")
bin/IRFinder: line 197: [: -lt: unary operator expected
bin/IRFinder: line 212: /proc/cpuinfo: No such file or directory
grep: /proc/cpuinfo: No such file or directory

And after the files have been ftp downloaded, I obtain another error related to /proc:
EXITING: fatal input ERROR: runThreadN must be >0, user-defined runThreadN=0

Is there a way to circumvent these errors or does IRFinder only run on Linux machines?
Thank you.
Best, 
AAM.

**Comment by dg520** [comment]
Hi AMM,

Seems to be a gcc version problem. Could you please run `gcc --version` in your terminal and pay attention to the first printed out line start with `Configured with ...`. IRFinder requires a GCC version above 4.9.0 to take advantage of C++ 11 features. 

If your GCC version is too old, you need to update your GCC version if it's your personal computer.

Best,
Dadi

**Comment by aambioinfo** [comment]
Dear Dadi, 

thank you for your reply. 
`gcc --version` shows 4.2.1
I have been trying to replace gcc version 4.2.1 that comes with Xcode with the 4.9 installed via Homebrew. 
I followed tips and comments posted in stackoverflow and other sites, and tried different solutions, but unsuccessfully (or so it seems) as I keep getting the same error when I run IRFinder (I am no sys admin and my knowledge in this matter is limited, so I may be doing something wrong). I will keep on trying to fix this.
Thank you again for your reply.
Best, 
AAM.

**Comment by dg520** [comment]
Hi @aambioinfo ,

Have you got trouble in installing GCC 4.9.0? Apologize that I'm not quite familiar with admin on MAC. But if you can start installing process, here is a nice [instruction:](https://stackoverflow.com/questions/28970935/osx-replace-gcc-version-4-2-1-with-4-9-installed-via-homebrew). Please follow the instruction in the best answer. Try Option 2 and Option 3 (both) he mentioned, that'll change your default C compiler to gcc 4.9.0.

If you encountered a permission deny problem to start/complete gcc install, there is limited we can due instead of asking for admin permission, although I think we can install gcc under user environment instead of under global system environment. 

Let me know if this is helpful.

Best,
Dadi

**Comment by aambioinfo** [comment]
Thanks Dadi, 
what you mention is what I had tried, and I still get the same error from my first message. I will try some other suggestions and see if I can make IRFinder work. Thank you very much for your help.
Best, 
AAM

**Comment by dg520** [comment]
Hi @aambioinfo ,

After installing GCC 4.9.0, if you call `gcc --version` again, does it show you an indication that 4.9.0 is in use? If it is in use, the error might be due to other system setting other than GCC (but GCC 4.9.0 is required anyway to successfully run IRFinder).

The error you encountered was due to that IRFinder was trying to figure out how much memory and how many threads it could use from the system but failed to find corresponding information.

Best,
Dadi

**Comment by aambioinfo** [comment]
Hi Dadi, 

yes, if now I call `gcc --version` it shows gcc-4.9 (Homebrew GCC 4.9.4) 4.9.4,  but the /proc related errors persist when running IRFinder.  As one answer in your link above mentions, calling `which gcc` still returns the Clang version, which is confusing (and I have not been able to change this as suggested by eeny), so I was not sure if I was doing things correctly.
So, if the proc/ information cannot be retrieved, STAR will fail to run, that is why I asked whether there was a way to circumvent these errors... maybe supplying this info in a different way.
Thanks, 
AAM.

**Comment by dg520** [comment]
Hi @aambioinfo ,

Could you please call IRFinder with `-t 1 -M 1000` option which will force IRFinder to use single thread for running and 1000MB memory for sorting? 

Cheers,
Dadi

**Comment by aambioinfo** [comment]
Hi Dadi, 

I did and now STAR is able to run and seems to be doing the mapping. I will let you know about the output I obtain. Thanks a lot for your help!

Best, 
Aida.

**Comment by dg520** [comment]
Hi Aida,

Did things turn out fine?

Best,
Dadi

**Comment by aambioinfo** [comment]
Hi Dadi,

STAR seems to run smoothly now, however, there are some warnings and "files not found":
Here I paste the std output so that you can see:

Sep 21 18:30:25 ..... started STAR run
Sep 21 18:30:25 ... starting to generate Genome files
Sep 21 18:31:25 ... starting to sort Suffix Array. This may take a long time...
Sep 21 18:31:39 ... sorting Suffix Array chunks and saving them to disk...
Sep 21 20:01:47 ... loading chunks from disk, packing SA...
Sep 21 20:03:05 ... finished generating suffix array
Sep 21 20:03:05 ... generating Suffix Array index
Sep 21 20:06:18 ... completed Suffix Array index
Sep 21 20:06:18 ..... processing annotations GTF
Sep 21 20:06:31 ..... inserting junctions into the genome indices
Sep 21 20:16:29 ... writing Genome to disk ...
Sep 21 20:16:32 ... writing Suffix Array to disk ...
Sep 21 20:16:58 ... writing SAindex to disk
Sep 21 20:17:01 ..... finished successfully
Star genome build result: 0
/Users/aam/APPLICATIONS/Programs/IRFinder-master_test/bin/util/Mapability: line 3: ulimit: max user processes: cannot modify limit: Invalid argument
Commence STAR mapping run for mapability.
Thu Sep 21 20:17:02 CEST 2017
awk: gzip -c1 > tmp_by_chr_32380/8.bed.gz makes too many open files
 input record number 199498975, file 
 source line number 1

real	190m22.087s
user	169m45.333s
sys	7m15.507s
Completed STAR run.
Thu Sep 21 23:27:24 CEST 2017
Commence Coverage calculation.
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]

real	0m0.006s
user	0m0.002s
sys	0m0.002s
cat: tmp_by_chr_32380/*.exclusion: No such file or directory

real	0m0.006s
user	0m0.004s
sys	0m0.004s
rm: tmp_by_chr_32380/*bed.gz.exclusion: No such file or directory
Completed coverage exclusion calculation.
Thu Sep 21 23:27:24 CEST 2017
Mapability result: 0
Build Ref 1
Build Ref 2
Build Ref 3
Build Ref 4
Build Ref 5
Build Ref 6
Build Ref 7
Build Ref 8
Build Ref 9
Build Ref 10
Build Ref 11
Build Ref 12
Build Ref 13b
Build Ref 14b
Build Ref 15b
Build Ref 16 - COMPLETE
Ref build result: 0
ALL DONE

**Comment by dg520** [comment]
Hi Aida,

I'm afraid reference preparation is not finished completely. IRFinder needs to open multiple files at the same time in order too achieve high-speed performance. The number of files allowed to be open is set by the admin when he builds the system. In most cases, this number is set to 65535 or unlimited. In you case, seems it's a small number, which is lower than what IRFinder needs, which is 4000. 

You can check this by type in terminal `ulimit -a` and pay attention to the number following `open files`. Try to run `ulimit -n 4001`. If it's prohibited, you need admin to increase that for you (if you are not an admin, you can only decrease the number, not increase). 

Please note that running downstream IRFinder analysis with an incomplete reference would be highly problematic. After increasing the limit, please re-run the reference preparation. A successful running should see no warning or error.

Best,
Dadi

**Comment by aambioinfo** [comment]
Hi Dadi, 

after increasing the number of open files to 4001 I get the same warnings, so I try and increase this to a higher figure.

Thanks, 
AAM

**Comment by aambioinfo** [comment]
Hi Dadi, 

after trying different open files limits (the last one `ulimit -n  60000`), I still obtain the "awk: gzip -c1 > tmp_by_chr_45447/8.bed.gz makes too many open files" error.  Could there be something else causing this error?

Thank you, 
AAM

**Comment by dg520** [comment]
Hi @aambioinfo ,

Sorry for a late reply. We're submitting a paper these days. I'll get back to you ASAP (probably next week). Will think about it meanwhile. 

Best,
Dadi

**Comment by dg520** [comment]
Hi @aambioinfo,

I cannot reproduce your error directly on my virtual machine of MAC OS. However, after playing a bit, I figured out several things might be helpful:
1) running `ulimit -n` only affects the current terminal window temporarily. That means, if you run IRFinder in another terminal window, the limit is reset to the original one;
2) in addition to `ulimit -n`, you also need to increase number of process by running `ulimit -u 4000`. Again, this is a temporary change and will be reset when the terminal is closed.
3) There are system-wide limits for how many files your system can open and how many processes you can have. You can check this by running `sysctl -w kern.maxfiles` and `sysctl -w kern.maxfilesperproc`. These two numbers should be larger than what you give to `ulimit -n` and `ulimit -u`. Otherwise you have to change them, which needs root permission. 

So please first check if your system-wide limits allows you to increase to `60000` and `4000`. And after running `ulimit -n 60000` and `ulimit -u 4000`, please run `ulimit -n` and `ulimit -u` again to double check if they return `60000` and `4000` respectively. And then run IRFinder in the SAME terminal window where you run `ulimit -n 60000` and `ulimit -u 4000`.

I hope this can get through the error you encountered. I apologize I'm not an expert of MAC and for the inconvenience in using IRFinder.

Best,
Dadi

**Comment by aambioinfo** [comment]
Hi Dadi, 

thanks a lot for your reply. What you mention is what I had been trying, although ulimit -u was 1024. I'm going to be away for a couple of weeks but when I'm back I will try to increase ulimit -u to 4000 as you recommend.
Thanks again.
Best, 
AAM

**Comment by aambioinfo** [comment]
Hi Dadi, 

I was finally able to increase `ulimit -u`, now  running `ulimit -a` shows:
Arecibo:IRFinder-master_test2 aida$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65000
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15000
virtual memory          (kbytes, -v) unlimited

Even with `ulimit -u` and `ulimit -n` returning 15000 and 65000 respectively,  I am still getting the "awk: gzip -c1 > tmp_by_chr_2269/8.bed.gz makes too many open files",
which is weird as `lsof` showed less than 6000 open files while STAR was running. 

Do you know how I could circumvent this problem with STAR (maybe use STAR and Bedtools in Galaxy and then use IRFinder with their output)? 
And, do you have any plans to do a wrapper of IRFinder to be used in Galaxy?
Thank you.
Best, 
AAM

**Comment by dg520** [comment]
Hi @aambioinfo,

I apologize to come back to you so late. It really wired system thinks too many files are opened after you increase the limitation. That might be some other factors in the system setting up that prevent IRFinder to run in a parallel matter. I’m not familiar with MAC OS. Really sorry I might not be able to help in this case. I would suggest you try to run it on a Linux Server. We currently do not have any plan to integrate IRFinder to GALAXY. 

Best,
Dadi

**Comment by aambioinfo** [comment]
Hi Dadi, 

thank you for your time and the information and help you have supplied. Currently, I do not have access to a Linux Server, but I am using Docker to run some programs that were problematic in Mac OS. Is there a IRFinder container available? 
Thanks again.

Best, 
AAM
