### ISSUE TITLE
BuildRefProcess mode problem

### ISSUE THREAD

**Issue by rachelf45** [williamritchie/IRFinder#31]
Hello Dadi,

I am having a problem with building the reference. Based on the other issues I have seen, it seems as if the STAR genome building process stops for some reason but does not throw up any errors, and then the mapping process cannot run because the files it needs were not generated. I have tried making the genome.fa and transcripts.gtf files from different ensembl releases, and I get the same problem. 

**My input is**

IRFinder -m BuildRefProcess -r REF/Mouse-mm10-release91

**The output is** 

Launching reference build process. The full build should take at least one hour.
Usage : /gpfs/gsfs8/users/liyan2/IRFinder-1.2.3/bin/util/IRFinder-BuildRefFromEnsembl mode threads STAR-executable base_ftp_url_of_ensembl_genome+gtf output_directory(must not exist) additional_genome_reference(eg: ERCC) non_polyA_genes-as-bed region_blacklist-as-bed
Usage example: /gpfs/gsfs8/users/liyan2/IRFinder-1.2.3/bin/util/IRFinder-BuildRe                             fFromEnsembl BuildRef 12 STAR "ftp://ftp.ensembl.org/pub/release-75/fasta/homo_s                             apiens/dna/" "IRFinder/REF/Human" "Refernce-ERCC.fa.gz" [non_polyA_genes.bed] [b                             lacklist.bed]
Dec 28 13:44:37 ..... started STAR run
Dec 28 13:44:37 ... starting to generate Genome files
Dec 28 13:46:47 ... starting to sort Suffix Array. This may take a long time...
Dec 28 13:47:16 ... sorting Suffix Array chunks and saving them to disk...
Star genome build result: 9
Commence STAR mapping run for mapability.
Thu Dec 28 13:51:22 EST 2017

EXITING because of FATAL ERROR: could not open genome file /REF/Mouse-mm10-release91/STAR/genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Dec 28 13:51:22 ...... FATAL ERROR, exiting

real    0m0.015s
user    0m0.001s
sys     0m0.003s
Completed STAR run.
Thu Dec 28 13:51:22 EST 2017
Commence Coverage calculation.
ls: cannot access tmp_by_chr_32182/*.bed.gz: No such file or directory

real    0m0.001s
user    0m0.000s
sys     0m0.002s
cat: tmp_by_chr_32182/*.exclusion: No such file or directory

real    0m0.203s
user    0m0.000s
sys     0m0.000s
rm: cannot remove `tmp_by_chr_32182/*bed.gz.exclusion': No such file or directory
rm: cannot remove `tmp_by_chr_32182/*bed.gz': No such file or directory
Completed coverage exclusion calculation.
Thu Dec 28 13:51:22 EST 2017
Mapability result: 0
Build Ref 1
Build Ref 2
Build Ref 3
Build Ref 4
Build Ref 5
Build Ref 6
Build Ref 7
Build Ref 8
Build Ref 9
Build Ref 10
Build Ref 11
Build Ref 12
Build Ref 13c
Build Ref 14c
Build Ref 16 - COMPLETE
Ref build result: 0
ALL DONE

Thank you for your attention,
Rachel

**Comment by dg520** [comment]
Hi Rachel,

I think the problem comes from STAR that failed to build genome reference. In your output above, there is one line: `Star genome build result: 9` which indicates an error during STAR genome reference building. Could you please check `log-star-build-ref.log` and other related STAR log files in your reference folder? If you cannot figure out the cause, please send me all your log files by email. My email address can be found on the bottom of Wiki page. 

Thanks a lot and happy new year!

Dadi

**Comment by lauriergray** [comment]
Hello Dadi -
I ran into a similar issue that was posted by Rachel.  After changing a parameter in my batch job script (SLURM ) I now have a different fatal error:
Launching reference build process. The full build should take at least one hour.
Usage : /sfs/nfs/apps/software/standard/compiler/gcc/7.1.0/irfinder/1.2.4/bin/util/IRFinder-BuildRefFromEnsembl mode threads STAR-executable base_ftp_url_of_ensembl_genome+gtf output_directory(must not exist) additional_genome_reference(eg: ERCC) non_polyA_genes-as-bed region_blacklist-as-bed
Usage example: /sfs/nfs/apps/software/standard/compiler/gcc/7.1.0/irfinder/1.2.4/bin/util/IRFinder-BuildRefFromEnsembl BuildRef 12 STAR "ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/" "IRFinder/REF/Human" "Refernce-ERCC.fa.gz" [non_polyA_genes.bed] [blacklist.bed]
May 15 20:38:40 ..... started STAR run
May 15 20:38:40 ... starting to generate Genome files

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 136410676608 and make that much RAM available 
Do you have a suggestion on how to solve this error? Thank you so much for your help.
Best,
Laurie

**Comment by dg520** [comment]
Hi Laurie,

Thanks for reporting. This is an issue from `STAR` instead of IRFinder. To my knowledge, STAR index for GRCh38 genome is quite memory consuming and needs to specify a larger memory allocation than default. If that's your case, you can follow `STAR` google group for more information. 

To you specific problem, you might wanna hack `IRFinder` code a bit by modifying `IRFinder/bin/util/IRFinder-BuildRefFromEnsembl`. Towards the very end of this script, there is a block:
```
my $starresult = system(
        $STAREXEC,
        "--runMode", "genomeGenerate",
        "--genomeDir", "$basedir/STAR",
        "--genomeFastaFiles", "$basedir/genome.fa",
        "--sjdbGTFfile", "$basedir/transcripts.gtf",
        "--sjdbOverhang", $sjdbOverlap,
        "--runThreadN", $threads,
        '&>>', "log-star-build-ref.log"
        );
```
This defines how IRFinder calls `STAR` to build genome reference index. You can insert other STAR parameters such as `--limitGenomeGenerateRAM` and its associated value into the block. Then run IRFinder genome preparation stage again. Let me know if you run into any further problem.

Best,
Dadi

**Comment by lauriergray** [comment]
Hi Dadi -
Thank you for the information.  After I posted, I took a step back to evaluate how I was submitting the job to our computer cluster. I increased the amount of memory needed for STAR in the job script and also re-downloaded HG38 and its appropriate GTF and it worked!  I'm now trying to solve why IRFinder won't recognize my paired sequences, but once again, it could be how I'm writing and submitting the job script.
Thank you again!
Best,
Laurie

**Comment by edkonyakhina** [comment]
Hello Dadi,
I have the same problem as rachelf45.
I tried to run STAR, using the same files and commands from IRFinder log.out files and it worked perfectly. But when I run IRFinder BuildProcess I have an error: 

Star genome build result: 9
Commence STAR mapping run for mapability.
Fri Jul 20 07:25:32 EDT 2018

EXITING because of FATAL ERROR: could not open genome file /home/ekonyakhina/IRFinder-1.2.4/REF/Human-hg38-release75/STAR/genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Jul 20 07:25:32 ...... FATAL ERROR, exiting

I attached all not-empty log files that I have according to this process. 
Did you solve rachelf45's problem? 



[Log.out.txt](https://github.com/williamritchie/IRFinder/files/2213815/Log.out.txt)
[Log.std.out.txt](https://github.com/williamritchie/IRFinder/files/2213816/Log.std.out.txt)
[Log1.out.txt](https://github.com/williamritchie/IRFinder/files/2213817/Log1.out.txt)

Many thanks,
Evgeniya

**Comment by dg520** [comment]
Hi @edkonyakhina ,

When IRFinder called STAR to build reference, it returned value 9 which means `The storage control block address is invalid`. It's also true in your `Log1.out.txt` file that STAR cannot save the parameters to the disk. So please make sure the version of IRFinder you're running has the permission to write to `/home/ekonyakhina/IRFinder-1.2.4/REF/Human-hg38-release75/STAR`.

Best,
Dadi

**Comment by dg520** [comment]
Hi Evgeniya,

Wired. If I understand correctly, `genomeParameters.txt` is the first file that is written to the disk during STAR reference building. Are you working on a cluster and submit IRFinder job through a queueing system? If so, could you please try to run IRFinder (reference building stage) directly without submitting to queue? Let me know how it turns out. 

Best,
Dadi

**Comment by edkonyakhina** [comment]
Hi Daddi,
Thank you for paying attention. STAR writes to this directory, but not all files, that are needed (for example, it doesn't write "genomeParameters.txt")

Many thanks,
Evgeniya

**Comment by edkonyakhina** [comment]
Hi Daddi,
Yes, I recognized that this problem was because of lack of memory. Thank you for your advice!

Best, 
Evgeniya
