### ISSUE TITLE
IRBase error occurs submitting example query

### ISSUE THREAD

**Issue by malcook** [williamritchie/IRFinder#36]
on page http://mimirna.centenary.org.au/irfinder/database/ the example form data when submitted throws error:

```
<type 'exceptions.IOError'>: [Errno 2] No such file or directory: '/srv/www/htdocs/irfinder/database/results/2018-04-05_c4sn2m7f/SRR496395/UBR4.txt' 
      args = (2, 'No such file or directory') 
      errno = 2 
      filename = '/srv/www/htdocs/irfinder/database/results/2018-04-05_c4sn2m7f/SRR496395/UBR4.txt' 
      message = '' 
      strerror = 'No such file or directory'
```

**Comment by dg520** [comment]
Hi @malcook ,

Thanks for using IRBase. IRBase was on the server of my PhD institute in Australia, which was partially broken last month. It has been rebuilt but I haven't test IRBase yet. 
I currently don't have the access permission to the server but I'll ask my colleague there to check. Will come back to you ASAP. Sorry for the inconvenience. 

Best,
Dadi

**Comment by malcook** [comment]
Thanks,

I Should’ve included in my report that IRBase contents are not really important to me, but thought I’d alert you.   I was more interested in what it looked like and whether I might borrow some ideas/code from it.  I’m currently reporting IR on a per experiment basis using ad-hoc reporting using Shiny and links to genome browser (IGV) for visual review.

I am really more interested in your glue to DESeq2 since as I understand it DESeq2 evaluates significance of changes in counts (i.e. readcounts/gene) across conditions while IR is fundamentally binomial, a ratio

I’m now looking at https://github.com/williamritchie/IRFinder/blob/master/bin/DESeq2Constructor.R  as well as Using RNA-seq DE methods to detect allele-specific expression<http://rpubs.com/mikelove/ase> for insight.

If you have any further source of insight into the approach for bridges this gap, I’d be obliged.

Thanks for IRFinder.  I hope your PhD went well.  Great topic!

~Malcolm

**Comment by dg520** [comment]
Hi @malcook,

The IRBase failed because the result folder on the server is full due to too many inquiries. My script that automatically cleans old inquiries is not functional, as my institute terminated my account after my graduation. I've asked my colleagues there with root permission to clean and take care of it in the future. It should be recovered in the next few days. 

Cheers,
Dadi

**Comment by malcook** [comment]
Aha, splendid, thanks for the news.

Regarding alternate/Baysian approaches…

I’m not super stats strong, but, this is what I’ve sussed out and tried in a past analysis:

For each intron: (for the moment, ignoring alternative splicing)

Count    Description
S              count of observations which support the spliced form (being, read alignments that have a gap in their alignment compatible with the intron)
A             count of observations which support intron retention occurring at the acceptor (3’) end of intron (being, alignments that extend at least one base into each side of the intron/exon boundary)
D             count of observations which support intron retention occurring at the donor (5’) end of intron (being, alignments that extend at least one base into each side of the exon/intron boundary)

Note: by the above, one alignment may be counted multiply – once for each form of evidence it provides

compute              formula                description
T                              = S+A+D               total reads
I                               = A+D                    read count supporting intron retention
PSI                          = I/(2S + I)           Percent Spliced In

I’ve then used bayesglm<https://www.rdocumentation.org/packages/arm/versions/1.9-3/topics/bayesglm> with quasibinomial distribution and T  (total reads) as “weight” which I understand is taken as number of trials<https://www.rdocumentation.org/packages/stats/versions/3.2.1/topics/glm> and so moderates the significance given expectation of higher variances at lower overall expression levels.

So, given experiment.df dataframe with columns S,A,D,T,I,PSI,expFactor1,expFactor2,…

What I had been doing is:

I<-seq(nrows(experiment.df))
f<-mclapply(i,function(i) {
  bayesglm(PSI ~ expFactor1 * expFactor2
          ,data= experiment.df[i,]
          ,weights= experiment.df[i]$T
          ,family='quasibinomial'
           )
})

The hits were biologically relevant and subsequently validated (alas only qualitatively) with PCR.

I am now extending the approach to taking alternative splicing into consideration, maintaining the notion of IR to be

PSI                          = I/(2S + I)

… except I and S are now the sum of all S,A,D observation across all junctions within a “spliceUnit” (basically groups of introns which connected by sharing an acceptor or donor).

Do you think this is in line with what your thoughts were?

I’m actually casting everything as SummarizedExperiment, so I should fairly easily be able to run DeSeq2, limma::voom, and contrast the results.

What do you think the best possibly evidence for which analysis is superior.  I suppose asking which has the best correlation coefficient with experimentally/qPCR determined results.   Is there any qPCR validated experimental dataset better than pasilla for this?

I really appreciate a sounding board, and your pointers in your docs to Love’s write-ups and how they influenced your thinking were very useful to shaping my thinking.

Any feedback welcome!

**Comment by dg520** [comment]
Hi @malcook,

IMO all your calculation for single IR (i.e. for single intron in each sample) is reasonable. The only concern is whether we should use total reads as the weight in the modeling. In terms of ration, 1 out of 10 should have the same weight as 10 out of 100. Maybe I have a wrong understanding of weight here, I haven't read the <bayesglm> manual yet. 

The major difficulty lies in how to model IR across samples, instead of the way to calculate single IR in one sample. As you pointed out earlier, IR is calculated as a ratio, so that logistic regression with (quasi-) binomial distribution is a good candidate at the first glance. 

However, a robust modeling is always based on enough observations. We need a sufficient sample size to estimate stable parameter sets for mean-and-variance relationship in each distribution assumption we made (i.e. dispersion parameters is critical for overdispersed data such as gene expression). Unfortunately, this is usually not the case in genetics. For example, a three-vs-three (e.g. 3 controls vs 3 treated) setup is far below sufficient level. If the parameter estimation is too random, the model will not state the ground truth but more likely to capture outliers. 

This is why DESeq2 is preferred in a lot of studies, as it's designed to overcome the under power problem in genetics. Still using the three-vs-three example and thinking of we're measuring gene expression, we would originally have 6 observations for each gene, where dispersion parameters cannot be stably estimated. However, Michael Love et al. found that we can borrow information from other genes, based on the observation that genes with similar expression level have similar dispersion. In that way, they "fakely" increases sample size for each gene.

Ideally, we want to borrow such information from other introns in the IR calculation. But I haven't found a pattern shared by different introns as what Love et al. found in gene expression. So for the moment, I would NOT recommend to use a general statistical modeling tool for IR modeling, EXCEPT when the sample size is really big, say 10-vs-10. I personally prefer sticking to DESeq2 and tweak it into ratios like what described in <http://rpubs.com/mikelove/ase>. Of course as a trade off, the test applied there is still based on the fold change of counts, instead of absolute change of ratio. 

To be more practically, modeling is the way lead to real biological discovery. Even if the model is imperfect, the strongest signals on the top should always be true. From my experience, DESeq2 is doing a good job in terms of that. And I always use qPCR validation of top signal as an indicator to the model quality.

A new statistical method is indeed wanted to solve this problem. I'll keep thinking of this but am not sure when it will come. Please follow the IRFinder update...

Best,
Dadi
