### ISSUE TITLE
Small bug in DESeq2Constructer: "assay colnames() must be NULL or equal colData rownames()"

### ISSUE THREAD

**Issue by mebbert** [williamritchie/IRFinder#39]
Hi,
I'm playing with IRFinder. Really appreciate your support.

I got the error from `SummarizedExperiment`:

> Error in FUN(X[[i]], ...) :
>   assay colnames() must be NULL or equal colData rownames()
> 
> traceback()
> 8: stop("assay colnames() must be NULL or equal colData rownames()")
> 7: FUN(X[[i]], ...)
> 6: vapply(assays, function(x) {
>        colnames <- colnames(x)
>        test <- is.null(colnames) || identical(colnames, ans_colnames)
>        if (!test)
>            stop("assay colnames() must be NULL or equal colData rownames()")
>        rownames <- rownames(x)
>        test <- test && is.null(rownames) || identical(rownames,
>            ans_rownames)
>        if (!test) {
>            txt <- "assay rownames() must be NULL or equal rowData rownames() /\n                    rowRanges names()"
>            stop(paste(strwrap(txt, exdent = 2), collapse = "\n"))
>        }
>        test
>    }, logical(1))
> 5: .local(assays, ...)
> 4: SummarizedExperiment(assays = SimpleList(counts = countData),
>        colData = colData, ...)
> 3: SummarizedExperiment(assays = SimpleList(counts = countData),
>        colData = colData, ...)
> 2: DESeqDataSetFromMatrix(countData = counts.IRFinder, colData = group,
>        design = designFormula) at DESeq2Constructor.R#37
> 1: DESeqDataSetFromIRFinder(filePaths = paths, designMatrix = experiment,
>        designFormula = ~1)

According to [a thread on Bioconductor](https://support.bioconductor.org/p/83850/), this is a fairly recent check enforced by `SummarizedExperiment` to make sure `colnames` of the counts matrix are identical to the `colData` `rownames` (or they must be null). I added the following line in `DESeq2Constructor.R` to set the rownames: `rownames(group) <- colnames(counts.IRFinder)`.

Let me know if you see any issues with this.

Best.

**Comment by dg520** [comment]
Hi @mebbert ,

Thanks for reporting this. I noticed this problem during development. In the example code on Wiki page, the design matrix was passed to `colData` without `rownames`. And it suggests user to check if the file order matches the sample order in design matrix before applying `DESeqDataSetFromIRFinder` function

I was thinking if I should add one line in `DESeqDataSetFromIRFinder` to force null `rownames` when read in design matrix and finally decided not to do that, because forcing that might cause messing up samples orders without warnings. I'm going to emphasize the importance of setting null `rownames` before passing the design matrix to `DESeqDataSetFromIRFinder` on the Wiki page.

I really appreciate your mining of IRFinder.

Best,
Dadi

**Comment by mebbert** [comment]
I may have misunderstood the error, but I think it requires setting the `colnames` to null. In either case, I think setting the `rownames` and `colnames` to be identical is probably most informative. Either way, the user has to make sure both are sorted properly. 

What may be safer is to have the user create *one* file with the path, sample names, treatment, etc., and then have your constructor split it for them. Then you know everything is sorted properly.

**Comment by mebbert** [comment]
@dg520,

Sorry for the slow response on this. My computer crashed shortly after I submitted this ticket, but I was using `DESeq2` and `SummarizedExperiment` from `Bioconducter 3.6`. I hope that's enough info.
