### ISSUE TITLE
Column header for IRFinder-IR-nondir.txt

### ISSUE THREAD

**Issue by lpantano** [williamritchie/IRFinder#43]
Hi!

thanks for creating and maintaining this tool!

I tried to find the headers for this file, but I couldn't find it.

I want to run IRfinder for just a couple of samples to know the intron retention percentage for some transcripts but I don't want to do differential expression analysis. Can you help me to know which file and value should I check on just to look at a metric that would tell me that for individual samples?

Thanks a lot!

**Comment by dg520** [comment]
Hi @lpantano ,

If your RNA libraries are non-directional, `IRFinder-IR-nondir.txt` is the file you're looking for. Otherwise, it's `IRFinder-IR-dir.txt`. A detailed description of file header can be found at: https://github.com/williamritchie/IRFinder/wiki/About-Main-Output-File

The 20th column (second last) is IR ratio you're interested in. I also recommend you to check column 19 (number of reads supporting the correct splicing of the junction) and column 8 (how much percentage of the entire intron length is covered by reads). For conservation, you might also wanna filter based on the warning information (e.g. only keep rows with "-" or "NonUniformIntronCover" in the last column).

Best,
Dadi

**Comment by lpantano** [comment]
Thanks! this is awesome!
