### ISSUE TITLE
Questions on total RNA seq data

### ISSUE THREAD

**Issue by amitbiochem04** [williamritchie/IRFinder#46]
Dear William, 
                   Recently, I came across to the IRFinder. I found very interesting. I have some issue with my data, I want to study the IR profile between Total RNA sequencing data vs Poly A selected sequencing. I don't have a typical condition like WT and KO. As you mentation in your manuscript that one must use Poly A selected RNA seq data. Could you please give some insight into this kind of issue. If I exclude Total RNA sequencing data and want to study only with Poly A selected data, can I make any sense? despite the fact, I can not test the differentially regulated IR gene, since I do not have a sample to compare with. Kindly let me know. I would really appreciate. 
Thank you very much. 
Kind regards, 
Aami

**Comment by dg520** [comment]
Hi Aami @amitbiochem04,

The reason to use polyA selected RNASeq is that we can assume the captured molecules belong to mature mRNA. So that the estimation of IR would be more likely to be true. On the other hand, ribo-minus libraries contain nascent RNAs, which will lead to an overestimated of true IR level. 

Additionally, comparing data between total RNASeq and polyA RNASeq would bring in many confounding factors due to different library preparation approach, not talking about batch effect itself yet. 

Although IR is calculated as a ratio between spliced and un-spliced reads where most compoundings should be cancelled out in terms of the mathematics, you might want to design the study carefully and investigate the result with high conservation.    

Best,
Dadi

**Comment by amitbiochem04** [comment]
Dear Dadi, 
                 Many thanks for your kind reply with suggestions. I have still doubts, I have some questions kindly help me out with this. From your answer, it is clear that I will not use Total RNA seq data. I have only polyA RNA seq data with replication. I do not have KO condition only have WT. If I want to find significant IR genes, then can I use IR ratio with a certain cutoff value? or it would bias the outcome. If I make a cutoff value then which would be the ideal value. I could see that many IR ratio value (20th column) is below 1( I run with 1.2.4 version, I do not see the header but I will switch to the 1.2.5). Or if you have some suggestion in this experimental scenario how can I get IR gene please let me know. 
I am waiting for your kind reply with anticipation.
Thank you very much.
Kind regards,
Aami

**Comment by dg520** [comment]
Hi Aami @amitbiochem04,

I guess you're talking about detecting IR events in your sample instead of finding differentially retained introns between conditions. You can surely do that. In our original Cell paper, we defined IR event as IR ration more than 0.1 (column 20) , with supported splicing reads more than 5 (column 19). You can also add more stringent filter such as a minimal intron coverage (column 8).

I'm not surprised that you found a lot of IR, even after filtering. As we found in the original paper, IR is quite common in a normal transcriptome. 

Best,
Dadi

**Comment by amitbiochem04** [comment]
Dear Dadi, 
                 Thank you very much for your prompt answer.  I guess you are referring to (https://www.sciencedirect.com/science/article/pii/S0092867413008349) this paper. 
I am sorry for asking several questions, this would be my last question :). Is it possible to detect the first intron in 5'end and last intron in 3' end?  I am interested only to detect those genes which retain only in either first intron in  5' or last intron in 3'end. Kindly let me know if it possible find this kind information.

Thank you very much. I am waiting for your kind reply with anticipation. 

Kind regards,
Aami

**Comment by dg520** [comment]
Hi Aami @amitbiochem04,

The first six columns of the main result file is in BED format, so that you can find coordinates of each intron measured. The fourth column contains the gene that contains that intron. From there, you have to figure out on your own whether the intron is at 5' or 3' end of a certain transcript of that gene. 

Best,
Dadi
