### ISSUE TITLE
missing intron events?

### ISSUE THREAD

**Issue by hliang** [williamritchie/IRFinder#48]
Hi,
I'm studying the intron retention ratio of a complex gene. It has 40+ transcript isoforms in the ensembl annotation (hg38). IRFinder finished without any error. In the result (IRFinder-IR-dir.txt), some of the introns are present, but a few are missing.

I think IRFinder makes the decision which introns to keep, when it builds the reference. Maybe IRFinder gets confused by so many isoforms. Would you explain why some introns are excluded?

Any suggestion if I really want to get the IR ratio of some missing introns? I'm thinking of building a gtf with a down-sized gtf file with less isoforms, maybe that makes IRFinder less confused. But I'm not sure which isoforms to include, because I don't know how IRFinder picks the good introns.

Thank you.

**Comment by dg520** [comment]
Hi @hliang ,

Nice update! Now it's much clearer what happened. First of all, the files with `exclude` mark where the genomic region should not be considered as "bona fide" introns So exonic regions are surely included. Other criteria such as low-mappability regions are added to the exclusion category as well (so will those regions defined in the black list that is passed to IRFinder). As we can obviously see from your IGV graph, the two introns of your interest have large chunks that would be masked out by IRFinder. The remaining "good" part is around 50% and 60% of the original length respectively.

In the script `IRFinder/bin/util/IntronExclusion.pl`, which is called by `IRFinder/bin/util/Build-BED-refs.sh`, there is a default cutoff setting for how long the minimal remaining part should be to let the intron to be kept. It's defined as minimal length of 40 bp and minimal ratio of 70% of the original intronic length, in the line: 
`if ($newlen > 40 && ($newlen/$len) >= 0.7) {`

Here is the solution specific to your case: 
1) First check if your introns of interest are contained in the file `tmp.candidate.introns`. They are unlikely to be missing there, otherwise we have to check the GTF/GFF file to begin with. 
2) You can change the above cutoffs to fit your intron of interest and re-run `IRFinder/bin/util/Build-BED-refs.sh`. Now you are supposed to find  them in `ref-cover.bed` and the 4th column is NOT `skip` .

Best,
Dadi

**Comment by hliang** [comment]
Dadi,
After I changed the threshold of `($newlen/$len)` in `IRFinder/bin/util/IntronExclusion.pl` from 0.7 to 0.4,  and reran `Build-BED-refs.sh`, the introns are now present in `ref-cover.bed`. See the IGV screenshot below, the introns of interest are marked by arrows. I include `ref-cover.bed` from default setting (upper panel) and modified setting (lower panel) for comparison.
![ref-cover bed](https://user-images.githubusercontent.com/812850/47535992-919b7580-d883-11e8-8ce8-b679f3cdadd8.png)
Thanks for your great help!

**Comment by dg520** [comment]
No problem. I hope IRFinder is useful to your project. I'll mark this discussion as `closed`.
