### ISSUE TITLE
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.

### ISSUE THREAD

**Issue by xiaoyonf** [williamritchie/IRFinder#50]
Hello,

I have the following modules installed in cluster: 3) gnu/gcc/4.9.3     5) irfinder/1.2.5
  2) star/2.6.1d       4) bedtools/2.27.1

I have builded reference genome under the REF subfolder, but I have the following error when I ran the command: 
IRFinder -r $IRFINDER_HOME/REF/Human-hg38-release81 -d MCF7L-FOXA1-Dox_irfinder MCF7L-FOXA1-Dox.fastq 

/share/apps/irfinder/1.2.5/bin/IRFinder: line 562: 12915 Broken pipe             "$STAREXEC" --genomeLoad $STARMEMORYMODE --runThreadN $THREADS --genomeDir "$REF/STAR" --outFilterMultimapNmax 1 --outSAMstrandField intronMotif --outFileNamePrefix "${OUTPUTDIR}/" --outSAMunmapped None --outSAMmode NoQS --outSAMtype BAM Unsorted --outStd BAM_Unsorted --readFilesIn "$1" $EXTRAREADFILESCOMMAND $EXTRAADAPT
     12916                       | tee "$OUTPUTDIR/Unsorted.bam"
     12917                       | gzip -cd
     12918 Aborted                 | "$LIBEXEC/irfinder" "$OUTPUTDIR" "$REF/IRFinder/ref-cover.bed" "$REF/IRFinder/ref-sj.ref" "$REF/IRFinder/ref-read-continues.ref" "$REF/IRFinder/ref-ROI.bed" "$OUTPUTDIR/unsorted.frag.bam" >> "$OUTPUTDIR/irfinder.stdout" 2>> "$OUTPUTDIR/irfinder.stderr"
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.

Can anybody help me out? It is my first time to use this app and really want to make it work.
Thanks a lot!

Xiaoyong

**Comment by xiaoyonf** [comment]
I also found a same issue posted before: https://github.com/williamritchie/IRFinder/issues/6#issue-224965736
It seems that this issue should be corrected in the new version of IRFinder. But I have the newest version 1.2.5. Please advise how to solve this problem.

**Comment by dg520** [comment]
Hi @xiaoyonf ,

This is not very informative. Looks like your process failed at reference preparation stage instead of analysis stage. Could you please send me the standard error printed on your screen when you run the reference building command?

And which version of bedtools are your using? Can you successfully call:
`bedtools genomecov` and `bedtools slop`? And which version of gcc are you using?

Best,
Dadi

**Comment by dg520** [comment]
Hi @xiaoyonf ,

The problem you encountered is due to the incompleteness of reference building, that's why you saw empty reference files, which leaded to the failure at analysis stage.  There are multiple steps during the reference preparation can cause this consequence. #6 you listed is just one of them, which has been fixed. 

Instead of quit immediately after encounter the error, IRFinder generate a summary of the status of each key step. So it might look like a completion for your architecture manger. 

I can see you are using a queuing system to run the job. Could you please re-run the reference preparation step and save the standard output and standard error to a separate file, so that I can help you to identify the broken point?

Best,
Dadi

**Comment by xiaoyonf** [comment]
Hi Dadi,

After re-ran the reference preparation step, the IRFinder function is up to run. Indeed, I think the previous reference was not built completely. Thank you for your help!
Best
Xiaoyong
