### ISSUE TITLE
irfinder.stderr

### ISSUE THREAD

**Issue by zhengjiantao** [williamritchie/IRFinder#56]
I got some errors in irfinder.stderr.
Input error at line:1
Characters read on last read call:0

And I had all 0 in irfinder.stdout. such as
![image](https://user-images.githubusercontent.com/41890364/54112307-d4b84880-4420-11e9-8cc2-6463f4d59410.png)

My data is single-end reads RNA-Seq data. My code is as following
IRFinder -m BuildRefProcess -r IRFinder/REF
IRFinder -m BAM -r IRFinder/REF -d IRFinder/xx xx.sortedByName.bam
What am I doing wrong?

**Comment by zhengjiantao** [comment]
@dg520

**Comment by dg520** [comment]
@zhengjiantao ,

First thing to check, is your BAM file recording chromosome as `chr1, chr2, ....` while your GTF file used to build genome reference is recoding chromosome as `1, 2, ....`? Or vise versa? They have to be in the same format.

If that's not the case, could you please provide me more information of your problem? Otherwise I can only guess what happened...Included but not limited to:
You system setup:
1. What's the version of your GCC? 
2. What's the version of your Bedtools? and STAR?
 
Your genome:
1. what species are your using here? Is it a well-annotated genome?
2. How many chromsomes and contigs in the GTF file?

Your RNASeq:
1. What protocol was used to generate RNASeq reads? Poly-A enriched or Ribo depletion?
2. What pipeline you've used to align your RNASeq reads? STAR or something else?
3. How many uniquely aligned reads you ended up with?

About IRFinder:
1. Did you encounter any problem when building the IRFinder reference. Is any file at `IRFinder/REF/IRFinder` empty?
2. Did you encounter any problem when you run the quantification step of IRFinder? 


Best,
Dadi

**Comment by zhengjiantao** [comment]
@dg520 
Thank you very much for your careful recovery.
I have checked all the items listed above. Including some of the details of STAR.
Ironically, the problem comes from parallelism in linux. I solved this using the "wait" command

Thanks again for your reply!
