### ISSUE TITLE
error in MacOS: ./IRFinder: line 550: ./util/irfinder: cannot execute binary file

### ISSUE THREAD

**Issue by aart127** [williamritchie/IRFinder#62]
Hi there. Please could you help with an issue calling IRFinder in bam mode? 
 
Mac Mojave 10.14.5 
gcc (Homebrew GCC 9.1.0) 9.1.0
bedtools v2.28.0

The reference was built under BuildRefProcess mode

server:bin roger$ ./IRFinder -t 1 -M 1000 -m BAM -r /Users/roger/Applications/IRFinder-1.2.5/REF/Human-hg19-release75 -d pooled_SL ~/Desktop/X4SL_unsorted.bam
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./IRFinder: line 193: /proc/meminfo: No such file or directory
./IRFinder: line 194: /1000: syntax error: operand expected (error token is "/1000")
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.

irfinder.stderr
./IRFinder: line 550: ./util/irfinder: cannot execute binary file

irfinder.stdout
IRFinder version: 1.2.4
IRFinder start:  Tue Jun 11 11:54:14 BST 2019
IRFinder runmode: BAM
IRFinder user@host: roger @ server.pvrg.private
IRFinder working dir:  /Users/roger/Applications/IRFinder-1.2.5/bin
IRFinder reference: /Users/roger/Applications/IRFinder-1.2.5/REF/Human-hg19-release75
IRFinder file 1: /Users/roger/Desktop/X4SL_unsorted.bam
IRFinder file 2: 

I've tried recompiling in src but get the following error:
server:irfinder roger$ make
hostname: illegal option -- -
usage: hostname [-fs] [name-of-host]
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Tue 11 Jun 2019 12:25:57 BST :/Users/roger/Applications/IRFinder-1.2.5/src/irfinder"'   FragmentBlocks.cpp
clang: error: unsupported option '-fopenmp'
make: *** [FragmentBlocks.o] Error 1

Sorry if this is something obvious - I'm new to this...

**Comment by dg520** [comment]
Hi @aart127 ,

I'm sorry to reply this late. I was finalizing a paper in the previous two weeks.
You encountered two MAC specific problems here:
1) When you run IRFinder with pre-compiled binaries, `readlink` on MAC does not support `-f` option.
2) When you tried to re-compile from source, the MAC default compiler `clang LLVM` does not support `openmp`. And in your case, you're still using clang instead of GCC 9.1.0 to compile. Please note, you do want to keep the default compiler to make other MAC software installation safe and easy.
The work around can be tricky on MAC OS. Among those, I recommend you to use a virtual environment. This makes your main system and environment is untouched if things did not work out eventually. If you're already using or familiar with `conda` or `anaconda`, the solution is more or less straightforward:
1) create a new conda environment for IRFinder and switch to that environment.
2) use `conda install` to install `gcc` and `llvm`.
3) compile IRFinder under this conda environment.
4) try to run IRFinder now. If it worked, remember to run IRFinder under this environment every time.

Let me know how it works. Apologize for the inconvenience. We didn't expect to run IRFinder on MAC or Windows.

Best,
Dadi
