### ISSUE TITLE
BuildRefProcess Possibly Failed?

### ISSUE THREAD

**Issue by suz11001** [williamritchie/IRFinder#63]
Hello,

I am trying to execute IRFinder on a VERY large genome, 32Gbps to be exact. Although I believe I allocated enough memory and cores (400G and 8 cores) to build the indices (took ~29 hours), I still received the following errors:

> awk: cmd. line:1: (FILENAME=- FNR=107663689) fatal: can't open pipe `gzip -c1 > tmp_by_chr_13577/fragScaff_scaffold_4449.bed.gz' for output (Too many open files)

The Mapability directory is not empty and the genomeParameters.txt  for STAR was successfully created. However, the following files are empty:
./IRFinder/ref-cover.bed
./IRFinder/exclude.directional.bed
./IRFinder/intergenic.ROI.bed
./IRFinder/ref-read-continues.ref
./IRFinder/ref-sj.ref
./IRFinder/introns.unique.bed
./IRFinder/ref-ROI.bed
./STAR/sjdbList.fromGTF.out.tab
./STAR/sjdbList.out.tab

So my first question is, did I build the reference correctly? I have attached a sample of the transcripts file I am using.
[transcripts.txt](https://github.com/williamritchie/IRFinder/files/3395476/transcripts.txt)

I tried to execute IRFinder regardless with the following command (50G mem and 16 cores):
`module load bamtools/2.5.1 
module load STAR/2.7.1a
module load BEDtools/2.27.1
module load gcc/4.9.1
module load libstdc++/6.0.13
~/IRFinder-1.2.3/bin/IRFinder -m BAM -r $REF -t 16 -d $out $bam`

However, this leads to the following error:

> /home/CAM/szaman/IRFinder-1.2.3/bin/IRFinder: line 561: 12976 Broken pipe             gzip -cd "$1"
     12977 Aborted                 | "$LIBEXEC/irfinder" "$OUTPUTDIR" "$REF/IRFinder/ref-cover.bed" "$REF/IRFinder/ref-sj.ref" "$REF/IRFinder/ref-read-continues.ref" "$REF/IRFinder/ref-ROI.bed" "$OUTPUTDIR/unsorted.frag.bam" >> "$OUTPUTDIR/irfinder.stdout" 2>> "$OUTPUTDIR/irfinder.stderr"

I see in the code that $LIBEXEC is set to $(dirname "$(readlink -nf "$BASH_SOURCE")")/util
However, when I try to execute this command, $LIBEXEC = ./util
Hence the environment variable $BASH_SOURCE does not exist in my shell. Is this a compiler issue? As you can see from my command, I am using GCC Version 4.9.1. Any guidance, would be much appreciated.

**Comment by dg520** [comment]
Hi @suz11001 ,

**Error 1: Reference building failed?**
Unfortunately, your genome of interest might be too big for IRFinder. When designing the building process of IRFinder reference, we decided to accelerate the job by analyzing chromosomes/scaffolds in parallel. There are multiple temporary files, each representing a chromosome/scaffold, open at the same time per process. However, the I/O system have a limitation on the number of files that is allowed to open at once (usually 65,535) and your system admin would probably further lower this limitation to protect the hardware. You can check this by `ulimit -n`. For normal genomes like human and mouse, this would never be a concern. But for huge genomes, it will end up with the error you encountered:
```
awk: cmd. line:1: (FILENAME=- FNR=107663689) fatal: can't open pipe `gzip -c1 > tmp_by_chr_13577/fragScaff_scaffold_4449.bed.gz' for output (Too many open files)
``` 
Would you mind check how many unique scaffolds are there for your genome?   And do you have enough space to open those altogether?  Is it possible to get rid of some scaffolds that are not informative in terms of gene expression?

And for the transcript file you attached, I'm not sure if you gave the IRFinder the same format. You must use a GTF-formatted file with attributes `transcript_biotype` and `gene_biotype` included in the last column (refer to Ensembl GTF files) to build the intron index during the IRFinder reference building. Please keep this in mind after get around the genome size problem

**Error 2: Execution failed?**
The error you encountered here simply suggested IRFinder cannot find content in the files it looks for, because your reference building failed. Nothing wrong with compilation at this stage, as far as I can tell. Unset `$BASH_SOURCE` is totally fine. The line `$(dirname "$(readlink -nf "$BASH_SOURCE")")` is used to figure out where is the `util` folder. If you don't have `$BASH_SOURCE`, IRFinder looks for the relative path where `IRFinder` stays. 

Best,
Dadi

**Comment by suz11001** [comment]
Hi Dadi, 

Thank you for the quick response! Although the genome is quite big, it has 16,468 scaffolds. Unfortunately, the number of files that can be simultaneously opened is 1024. I will try to see if I can increase this limit during a job submission. Thank you for pointing out the problem with the GTF, I will additionally add the transcript biotype tag as well.

Your guidance is much appreciated!

Sincerely,

Sumaira

**Comment by suz11001** [comment]
Hi Dadi,

I was looking at the Human Ensemble annotation located here: 
ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz

However, I do not see the attribute `transcript biotype` in the gtf, could you please let me know which features (mRNA, exon, etc) is supposed to have this tag. 

Sincerely,

Sumaira
Sumaira

**Comment by dg520** [comment]
Hi @suz11001 ,

I believe `Homo_sapiens.GRCh37.75.gtf` from Ensembl should either have `transcript_biotype` or `gene_biotype` or `gene_type`. 

Please note, IRFinder builds intron index only if there is at least one of these attributes in the gtf line, and only if the value of the attribute is `protein_coding` or `processed_transcript`.

Best,
Dadi
