### ISSUE TITLE
outout files for differential IR

### ISSUE THREAD

**Issue by qicaibiology** [williamritchie/IRFinder#84]
Hi @dg520 :

Sorry to disturb again! I have 2 questions on the output file of IRFinder:
1. by looking into the out file of DIV0 Vs DIV7 (each 2 replicates), I saw there are 3 p values: p-diff, p-increased, p-decreased: my interpretation is that: p-diff is the meaning for significance of the differential intron retention; p-increased is the confidence of to what extent the intron retention is increased(1 means almost 100% confidence?); whereas p-decrease mean the opposite of the p-increase. (I tried to read the Audic-Claverie paper cited in the manual about the comparison meaning, but have not been able to appreciate yet).
2. when I use directed sequence files, I saw in the output including a file named "IRFinder-IR-nondir.txt". By looking into the content, it looks that this file shows the content as roughly the same with "IRFinder-IR-dir.txt" with slightly different row numbers, and sometimes labeling like "antiover". When doing the downstream analysis. How should I deal with this file when doing comparison though it is not used in the manual?

Thanks a lot for your help,

Cai

**Comment by dg520** [comment]
Hi @qicaibiology ,

1. When you compare two samples, one samples is used as a baseline. all these p values tell you how significant the corresponding comparison is:
    `p-diff` tells you how different the two IR values are between the two samples, no matter increase or decrease. You can consider this is the summary/minimum of the other two p values 
    `p-increase` tells you the significance of IR increase in the second sample compared to the baseline sample.
    `p-increas` tells you the significance of IR decrease in the second sample compared to the baseline sample.

2. As I said before, IRFinder determines your library directionality automatically. If it thinks your library is directional, it will generated both `IRFinder-IR-nondir.txt` and `IRFinder-IR-dir.txt`. They are generated according to non-directional reference and directional reference respectively. That's why we see `antiover` tags in the `IRFinder-IR-dir.txt`. That is the tag only exists in the directional reference. When you doing your downstream comparison, you should ask yourself, whether your library is directional or not:
    If it is directional, and IRFinder gives `IRFinder-IR-dir.txt`, I highly recommend you always refer to `IRFinder-IR-dir.txt`.
    If it is non-directional, there should only be one output, which is `IRFinder-IR-nondir.txt`. You definitely always use that one for your analysis.
    If you don't know your library directionality, for example, you use public available data, you can trust the judgement by IRFinder. If it gives you `IRFinder-IR-dir.txt`, use it. 
    If you believe the directionality is different between what you know and what IRFinder reports, let me know.

**Comment by qicaibiology** [comment]
Hi @dg520 :

Thanks a lot for your explanation!

Cai
