### ISSUE TITLE
p-diff explanation 

### ISSUE THREAD

**Issue by ojziff** [williamritchie/IRFinder#99]
Hi there,

I can't find the column explanation for the output of analysisWithLowReplicates.pl in https://github.com/williamritchie/IRFinder/wiki/IRFinder-Output. I am specifically looking for an explanation of p-diff, p-increased and p-decreased. Is p-diff the adjusted p value comparing the IR ratio in condition A vs condition B?

Is there a measure of differential **effect size** in the output or would you suggest we calculate a delta IRratio between conditions simply as `A.IRratio - B.IRratio`?

Many thanks for your help,
Oliver

**Comment by dg520** [comment]
Hi @ojziff ,

`p-diff` is the final p-value you should consider as the statistical result for your analysis. It tells whether there is a significant IR difference (two-tailed) between the two conditions using Audic and Claverie Test. 
`p-increase` and `p-decrease` just tells whether the `p-diff` indicates an IR increase or decrease respectively, instead of re-applying a one-tailed test. Therefore, one of `p-increase` and `p-decrease` should equal `p-differ` while the other equals (1-p-diff). 

For the effect size of a specific IR event, you can simply use (average IR of that event in condition A - average IR of that event in condition B), as what you've mentioned.

Best,
Dadi

**Comment by ojziff** [comment]
Hi @dg520

Sorry to reopen this - is the p-diff adjusted for multiple comparisons?

Many thanks,
Oliver

**Comment by dg520** [comment]
@ojziff No, they are not.
